spring:
  application:
    name: Hello
  datasource:
    url: jdbc:postgresql://localhost:5432/projections-examples
    username: user
    password: password
    driver-class-name: org.postgresql.Driver